### ISSUE TITLE
F-Droid build failed: GMS in the final apk

### ISSUE THREAD

**Issue by linsui** [Sangwan5688/BlackHole#345]
```
2022-06-19 05:30:47,542 DEBUG: > /opt/android-sdk/build-tools/31.0.0/dexdump /tmp/tmppyqqmu2r/classes.dex
2022-06-19 05:30:50,745 DEBUG: Found class 'com/google/android/play/core/splitinstall/SplitInstallManager'
2022-06-19 05:30:50,748 DEBUG: Found class 'com/google/android/play/core/splitinstall/SplitInstallSessionState'
2022-06-19 05:30:50,749 DEBUG: Found class 'com/google/android/play/core/splitinstall/SplitInstallStateUpdatedListener'
2022-06-19 05:30:50,752 DEBUG: Found class 'com/google/android/play/core/tasks/OnFailureListener'
2022-06-19 05:30:50,753 DEBUG: Found class 'com/google/android/play/core/splitcompat/SplitCompatApplication'
2022-06-19 05:30:50,755 DEBUG: Found class 'com/google/android/play/core/tasks/OnSuccessListener'
2022-06-19 05:30:50,756 CRITICAL: Found problems in build/com.shadow.blackhole/build/app/outputs/flutter-apk/app-release.apk
2022-06-19 05:30:50,874 ERROR: Could not build app com.shadow.blackhole: Found blocklisted packages in final apk!
```

This is usually caused by the proguard but I didn't find it in this repo. See https://gitlab.com/famedly/fluffychat/-/merge_requests/875. Could you please take a look? Thanks!

**Comment by Sangwan5688** [comment]
Umm, so this was caused in the latest version only and not the previous version? Ig it was caused by the arch tracking which is done to install a platform-specific version while updating the app. Are there any workarounds around the same or will I need to completely remove it??

**Comment by Sangwan5688** [comment]
Ok, looks like it was a package issue which has been resolved. Will update it.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/2731835101 I test with the master and the problem is still there.

**Comment by Sangwan5688** [comment]
Umm, it shouldn't be there. I will have to check

**Comment by Sangwan5688** [comment]
@linsui can you try again with the latest version, lemme know if problem still persists. I have updated the package to latest version. I'm not sure if its completely removed it in that package or not. But they claim that they have completely removed it now.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/2961203854 Those classes still exist.

**Comment by doubledge-spec** [comment]
Any update on this? Avid F-Droid user here.

**Comment by linsui** [comment]
I tried the new version but it still has the classes in the apk.

**Comment by Sangwan5688** [comment]
I'm not sure which version of the package is compatible with F-droid. So, I have removed the package itself from the app. This won't cause any issue for F-droid users, but users who download from other sources will have a slight inconvenience installing the apk for the right arch. But that's fine ig. @linsui Can you verify if the issue is resolved?

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/3540576004 Still no luck. The classes are from Flutter itself but I don't know why they are kept in the apk.

**Comment by Sangwan5688** [comment]
@linsui I checked the previous versions of the app and it seems like they had these classes too. But still the app passed the check previously. Are these classes added recently??

**Comment by linsui** [comment]
No. We added a binary scanner recently which found those classes in the apks. In the past we only scan the source code and for Flutter apps we basically scan nothing.

**Comment by linsui** [comment]
Do you enable any options for the app? Only about 10 apps have these classes in the apks. I don't know why but I guess that's due to some build options.

**Comment by Sangwan5688** [comment]
I doubt I have enabled anything extra other than device_info which was used by the app to check device arch and suggest respective split apk on update. But I have removed that too. Other than that I doubt there's anything that might use these classes.

**Comment by Sangwan5688** [comment]
I suspect these can be classes from `dart:io` which is inbuilt in flutter itself. That is used to check if the platform is Android, iOS or anything else as flutter support different platforms so sometimes we do want to do something respective to a platform.

**Comment by linsui** [comment]
device_info is also used in many other apps so I doubt it's the problem.

> I suspect these can be classes from dart:io which is inbuilt in flutter itself. 

Is this function rarely used? Most flutter apps doesn't have these classes in the apk. If I understand it correctly, the classes are stripped out if the function is not used.

**Comment by Sangwan5688** [comment]
> Is this function rarely used?

Not really, it's actually quite common to do so if you are creating a cross platform app.
>  If I understand it correctly, the classes are stripped out if the function is not used.

Yup.
Do we have something in [pubspec.yaml](https://github.com/Sangwan5688/BlackHole/blob/main/pubspec.yaml) file which is common in other apps which are failing? and is not present in apps which passed the build.

**Comment by linsui** [comment]
I thought only 2 apps with this problem haven't been fixed. Another one is https://github.com/FredJul/Warmd/issues/52.

You can search flutter in https://gitlab.com/fdroid/fdroidserver/-/issues/1004. Other apps are fixed with the proguard trick.

**Comment by Sangwan5688** [comment]
Cool, I finally got the issue. It's caused by `audiotagger` package which is being used currently to add tags to media files. Ig the proguard file in that package have some issues. Anyways, I can't directly remove the package right now as it's necessary for the download functionality of this app. I'll probably try raising an issue or even a PR if possible for that package. If not then I'll just create a fork of the same for our use case. Thanks for all the info.

**Comment by Sangwan5688** [comment]
So, `flutter.io.app` has the class `FlutterPlayStoreSplitApplication` (Ref: https://api.flutter.dev/javadoc/io/flutter/app/FlutterPlayStoreSplitApplication.html) and apparently the package audiotagger is including all classes present in `flutter.io.app`. Ref: https://github.com/Samurai016/Audiotagger/blob/master/android/proguard-rules.pro

**Comment by linsui** [comment]
Wow, great! How do you find that?

> Anyways, I can't directly remove the package right now as it's necessary for the download functionality of this app. I'll probably try raising an issue or even a PR if possible for that package. If not then I'll just create a fork of the same for our use case.

We can simply patch the proguard file for that package. Is it enough to remove that line?

**Comment by Sangwan5688** [comment]
I have just created a fork of the package and edited proguard file in that one. (https://github.com/Sangwan5688/Audiotagger). Have even switched to this repo instead of the official one. Can you try trigger the build now? Ig it should work fine now.

**Comment by linsui** [comment]
It works! Thanks! I'll update the metadata later.

**Comment by Sangwan5688** [comment]
Cool, closing this issue then.
