### ISSUE TITLE
Can't import music from Spotify 

### ISSUE THREAD

**Issue by Ptvimal** [Sangwan5688/BlackHole#365]
![Uploading Screenshot_20220707-163758.jpg…]()
This is the issue I am facing while importing from Spotify

**Comment by Sangwan5688** [comment]
fixed with [dd51af9](https://github.com/Sangwan5688/BlackHole/commit/dd51af900bdd0ff23f8f9ce79c6a7f291c68f768)

**Comment by Ptvimal** [comment]
![Screenshot_20220721-170749](https://user-images.githubusercontent.com/109137652/180204842-49be81bb-d725-4486-bb07-70409fd1a52f.png)


This issue is not fixed,while importing from Spotify
